### ISSUE TITLE
Is there documentation?

### ISSUE THREAD

**Issue by Extractivity** [dsielab/generator-module#1]
Cheers. This package looks promising; is there any documentation or maybe a tutorial for it? Thank you.

**Comment by pachidj87** [comment]
Greetings.
There are no documentation yet. But I am working on it.
If you have some questions, I will be glad to help.

**Comment by Extractivity** [comment]
Hello pachidj87, thanks for your response.

I'm trying to generate CRUD api and scaffolding inside an existing module `FooManager`, based on an existing table `FooTable`. So, I first installed the package with:

`composer require dsielab/generator-module`

and attached the module with

`php artisan generate:module-use FooManager`

Now I tried to generate files, using

`php artisan generate:api_scaffold
	--tableName=FooTable
	--fromTable
	--save
	--softDelete
	--factory
	--seeder
	--localized
	FooModel
`

but get the following exception:

`
ErrorException  : array_walk() expects parameter 1 to be array, null given at [...]/vendor/dsielab/generator-module/Common/GeneratorConfig.php:121
`

The array `$modulePaths` in line 121 actually turns out to be empty, which leads me to believe I skipped a step somewhere. When I look at the configuration via `dd(config());` right before that line, the `modules.generator` configuration object does not exist.

Thanks for your help. :)

**Comment by pachidj87** [comment]
First 
- remove totally the installation of the generator
- try to install `joshbrw/laravel-module-installer`
- then install `nwidart/laravel-modules` and `infyomlabs/laravel-generator` by following these modules docs
- then when you install `dsielab/generator-module` you will see it in `modules/Generator` folder
- finally do `php artisan vendor:publish`

Then try again your api_scaffold generation.

Thank you for triying the package. I am sure we could improve it to make better stuffs.

**Comment by Extractivity** [comment]
Thank you for the advice. I was able to get the Generator module using your order, but haven't managed to properly build the scaffold so far. I'll keep on trying. :)
