### ISSUE TITLE
ModuleMakeCommand::handle() must be compatible

### ISSUE THREAD

**Issue by askippers** [dsielab/generator-module#3]
When trying to composer install, I get: 

PHP Fatal error:  Declaration of Modules\Generator\Console\Module\ModuleMakeCommand::handle() must be compatible with Nwidart\Modules\Commands\ModuleMakeCommand::handle(): int in /Users/ashley/code/govdata/vendor/dsielab/generator-module/Commands/Module/ModuleMakeCommand.php on line 27

   Symfony\Component\ErrorHandler\Error\FatalError

  Declaration of Modules\Generator\Console\Module\ModuleMakeCommand::handle() must be compatible with Nwidart\Modules\Commands\ModuleMakeCommand::handle(): int

  at vendor/dsielab/generator-module/Commands/Module/ModuleMakeCommand.php:27
    23|
    24|     /**
    25|      * Execute the console command.
    26|      */
  > 27|     public function handle()
    28|     {
    29|         $names = $this->argument('name');
    30|
    31|         if (!$names) {

   Whoops\Exception\ErrorException

  Declaration of Modules\Generator\Console\Module\ModuleMakeCommand::handle() must be compatible with Nwidart\Modules\Commands\ModuleMakeCommand::handle(): int

  at vendor/dsielab/generator-module/Commands/Module/ModuleMakeCommand.php:27
    23|
    24|     /**
    25|      * Execute the console command.
    26|      */
  > 27|     public function handle()
    28|     {
    29|         $names = $this->argument('name');
    30|
    31|         if (!$names) {

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()

**Comment by pachidj87** [comment]
Thank you @askippers, I just push a little change. Please update and let me know if it works for you.
